USE truonghoc;
INSERT INTO bachoc VALUES ("TX", "Giáo dục thường xuyên");
INSERT INTO bachoc VALUES ("MN", "Mầm non");
INSERT INTO bachoc VALUES ("TH", "Tiểu học");
INSERT INTO bachoc VALUES ("CS", "Trung học cơ sở");
INSERT INTO bachoc VALUES ("PT", "Trung học phổ thông");
INSERT INTO loaitruong VALUES ("XXXXXX", NULL);
INSERT INTO loaitruong VALUES ("GDTX", "TT GDTX");
INSERT INTO loaitruong VALUES ("GDNN", "TT GDNN");
INSERT INTO loaitruong VALUES ("NN-TX", "TT GDNN - GDTX (Sát nhập theo TTLT số 39/2015)");
INSERT INTO loaitruong VALUES ("PT", "Trường phổ thông");
INSERT INTO loaitruong VALUES ("DT", "Dân tộc bán trú");
INSERT INTO loaitruong VALUES ("NKTT", "Năng khiếu thể dục thể thao");
INSERT INTO loaitruong VALUES ("CH", "Trường chuyên");
INSERT INTO loaihinh VALUES ("CL", "Công lập");
INSERT INTO loaihinh VALUES ("DL", "Dân lập");
INSERT INTO loaihinh VALUES ("TT", "Tư thục");
INSERT INTO loaihinh VALUES ("UN", "Unknown");
INSERT INTO phonggd VALUES ("q01", "Phòng GDĐT quận 1");
INSERT INTO phonggd VALUES ("q02", "Phòng GDĐT quận 2");
INSERT INTO phonggd VALUES ("q03", "Phòng GDĐT quận 3");
INSERT INTO phonggd VALUES ("q04", "Phòng GDĐT quận 4");
INSERT INTO phonggd VALUES ("q05", "Phòng GDĐT quận 5");
INSERT INTO phonggd VALUES ("q06", "Phòng GDĐT quận 6");
INSERT INTO phonggd VALUES ("q07", "Phòng GDĐT quận 7");
INSERT INTO phonggd VALUES ("q08", "Phòng GDĐT quận 8");
INSERT INTO phonggd VALUES ("q09", "Phòng GDĐT quận 9");
INSERT INTO phonggd VALUES ("q10", "Phòng GDĐT quận 10");
INSERT INTO phonggd VALUES ("q11", "Phòng GDĐT quận 11");
INSERT INTO phonggd VALUES ("q12", "Phòng GDĐT quận 12");
INSERT INTO phonggd VALUES ("ccu", "Phòng GDĐT Củ Chi");
INSERT INTO phonggd VALUES ("bch", "Phòng GDĐT Bình Chánh");
INSERT INTO phonggd VALUES ("tdu", "Phòng GDĐT Thủ Đức");
INSERT INTO phonggd VALUES ("bth", "Phòng GDĐT Bình Thạnh");
INSERT INTO phonggd VALUES ("gva", "Phòng GDĐT Gò Vấp");
INSERT INTO phonggd VALUES ("hmo", "Phòng GDĐT Hóc Môn");
INSERT INTO phonggd VALUES ("tph", "Phòng GDĐT Tân Phú");
INSERT INTO phonggd VALUES ("bta", "Phòng GDĐT Bình Tân");
INSERT INTO phonggd VALUES ("tbi", "Phòng GDĐT Tân Bình");
INSERT INTO phonggd VALUES ("nbe", "Phòng GDĐT Nhà Bè");
INSERT INTO phonggd VALUES ("cgi", "Phòng GDĐT Cần Giờ");
INSERT INTO phonggd VALUES ("pnh", "Phòng GDĐT Phú Nhuận");
INSERT INTO phonggd VALUES ("XXX", NULL);
